title: Intermedios

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Intermedios"

permalink: /intermedios/:title.html

prose:
  ignore: [
    '_layouts',
    'css',
    '.git',
    'vendor',
    'package-lock.json',
    'package.json',
    'js',
    'gulpfile.js',
    '.gitignore',
    '_site'
  ]
  siteurl: "https://escueladominical.github.io/"
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Ingrese el título de su clase
          type: text
      - name: date
        field:
          element: text
          label: Fecha de la Publicación
          value: CURRENT_DATETIME
      - name: image-master
        field:
          element: text
          label: Ingrese una imagen para el detalle de su publicación
          value: img/
      - name: image-detail
        field:
          element: text
          label: Ingrese una imagen para el detalle de su publicación
          value: img/
      - name: verso-biblico
        field:
          element: text
          label: Ingrese el versículo central de su clase
      - name: published
        field:
          element: checkbox
          label: Publicar
          help: Puede elegir entre publicar o guardar su trabajo para continuar luego.
          value: false
